pipeline {
    agent {
        label 'devopseng1'
    }
    stages {
        stage ('git') {
            steps {
            git 'https://github.com/kovasorov/nwrp.git'
            }
        }
        stage ('build') {
            steps {
                sh 'mvn package'
            }
        }
        stage ('deploy') {
            steps {
                sh 'scp /tmp/workspace/df/target/hello-1.0.war devops@192.168.1.107:/tmp'
            }
        }

    }
}